# Generated by Django 4.2.7 on 2023-12-11 15:14

import create_track_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_track_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'ordering': ['-order_placed'], 'verbose_name': 'Order details', 'verbose_name_plural': 'Order details'},
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(blank=True, choices=[('order_placed', 'Order Placed'), ('order_prepared', 'Order Prepared'), ('order_completed', 'Order Completed'), ('order_paid', 'Order Paid')], default='order_placed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.CharField(blank=True, default=create_track_orders.models.id_generator, max_length=6, null=True, unique=True),
        ),
    ]
