apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  DATABASE_NAME: bG91bmdlLWRhdGE=
  DATABASE_USER: Z2F1dGhhbXN1  # Adjust username
  DATABASE_PASSWORD: S2FhbGFiaGFpcmF2YTEh  # Replace with actual password