# Generated by Django 4.2.7 on 2024-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_userprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Closed', 'Closed')], max_length=10, null=True)),
                ('leave_details', models.TextField(blank=True, max_length=100, null=True)),
                ('leave_start_date', models.DateTimeField()),
                ('leave_end_date', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('employee', models.ManyToManyField(to='employee.userprofile')),
            ],
        ),
    ]
