# Generated by Django 4.2.7 on 2024-01-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeeleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleave',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.userprofile'),
        ),
    ]
