# Generated by Django 4.2.7 on 2024-01-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0008_remove_employeeleave_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'ordering': ('leave_start_date',)},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, choices=[('Kitchen', 'Kitchen'), ('Floor', 'Floor'), ('Admin', 'Admin')], null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
