# Generated by Django 4.2.7 on 2024-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_track_orders', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
