# Generated by Django 4.2.7 on 2024-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug_title', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='dish_images/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_non_veg', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.CharField(blank=True, choices=[('FOOD', 'FOOD'), ('DRINKS', 'DRINKS'), ('HOOKAH', 'HOOKAH')], default='FOOD', max_length=20, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Mocktail', 'Mocktail'), ('Milkshake', 'Milkshake'), ('Hot Beverages', 'Hot Beverages'), ('Hookah', 'Hookah')], default='Starter', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Menu items',
                'verbose_name_plural': 'Menu items',
            },
        ),
    ]
