apiVersion: v1
kind: Service
metadata:
  name: lounge-app-service
spec:
  type: ClusterIP  # Adjust if needed (e.g. NodePort)
  selector:
    app: lounge-app
  ports:
  - protocol: TCP
    port: 8000  # External port
    targetPort: 8000  # Port exposed by the container
