# Generated by Django 4.2.7 on 2023-11-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_non_veg',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
