# Generated by Django 4.2.7 on 2023-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitems_category_alter_menuitems_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Mockatail', 'Mocktail'), ('Milkshake', 'Milkshake'), ('Hot Beverages', 'Hot Beverages'), ('Hookah', 'Hookah')], default='Starter', max_length=20, null=True),
        ),
    ]
