# Generated by Django 4.2.7 on 2023-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitems_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='slug_title',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='is_non_veg',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
