# Generated by Django 4.2.7 on 2023-12-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitems_slug_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name': 'Menu items', 'verbose_name_plural': 'Menu items'},
        ),
    ]
