# Generated by Django 4.2.7 on 2024-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Mocktail', 'Mocktail'), ('Milkshake', 'Milkshake'), ('Hot Beverages', 'Hot Beverages'), ('Hookah', 'Hookah')], default='Starter', max_length=20, null=True),
        ),
    ]
