# Generated by Django 4.2.7 on 2023-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
