# Generated by Django 4.2.7 on 2023-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetails_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_prepared', 'Order Prepared'), ('order_completed', 'Order Completed'), ('order_paid', 'Order Paid')], default='order_placed', max_length=20),
        ),
    ]
