# Generated by Django 4.2.7 on 2024-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/profile.png', null=True, upload_to='profile_images'),
        ),
    ]
